/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.is2022g33.componentes;

import com.is2022g33.helpers.Cliente;

/**
 *
 * @author marcos
 */
public class ListaClientes extends javax.swing.JPanel {

    private Cliente[] clientes;

    public ListaClientes() {
        this(10);
    }
    
    /**
     * Creates new form ListaClientes
     */
    public ListaClientes(int number) {
        initComponents();
        clientes = Cliente.getClientes(number);
        this.setClientes();
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(180);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(70);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private String[][] formatClientes() {
        String[][] str = new String[clientes.length][3];

        for (int i = 0; i < clientes.length; i++) {
            str[i][0] = clientes[i].nombre;
            str[i][1] = clientes[i].apellidos;
            str[i][2] = clientes[i].dni;
        }

        return str;
    }

    private void setClientes() {
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                this.formatClientes(),
                new String[]{
                    "Nombre", "Apellidos", "DNI"
                }
        ));
    }
    
    private void setClientes(Cliente[] clientes) {
        this.clientes = clientes;
        
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                this.formatClientes(),
                new String[]{
                    "Nombre", "Apellidos", "DNI"
                }
        ));
    }
    
    private Cliente[] getClientes(){
        return clientes;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
