/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.is2022g33.componentes;

import com.is2022g33.helpers.Persona;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 *
 * @author marcos
 */
public class ListaPersonas extends javax.swing.JPanel {

    private Persona[] personas;

    public ListaPersonas() {
        this(10);
    }

    /**
     * Creates new form ListaClientes
     *
     * @param number
     */
    public ListaPersonas(int number) {
        this(Persona.getPersonas(number));
    }

    public ListaPersonas(Persona[] personas) {
        this.personas = personas;
        initComponents();
        this.setPersonas();
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(65);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(80);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private String[][] formatClientes() {
        String[][] str = new String[personas.length][3];

        for (int i = 0; i < personas.length; i++) {
            str[i][0] = personas[i].nombre;
            str[i][1] = personas[i].apellidos;
            str[i][2] = personas[i].dni;
        }

        return str;
    }

    private void setPersonas() {
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                this.formatClientes(),
                new String[]{
                    "Nombre", "Apellidos", "DNI"
                }
        ));
    }

    public void setPersonas(Persona[] personas) {
        this.personas = personas;

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                this.formatClientes(),
                new String[]{
                    "Nombre", "Apellidos", "DNI"
                }
        ));
    }

    private Persona[] getPersonas() {
        return personas;
    }

    private Persona getSelectedPersona() {
        return jTable1.getSelectedRow() == -1 ? null : personas[jTable1.getSelectedRow()];
    }
    
    public void filterDni(String dni){
        List<Persona> filtra = new ArrayList<>(Arrays.asList(personas));
        
        for(int i = filtra.size()-1; i>=0; i--)
            if(!filtra.get(i).dni.startsWith(dni))
                filtra.remove(i);
        
        String[][] str = new String[personas.length][3];

        for (int i = 0; i < filtra.size(); i++) {
            str[i][0] = filtra.get(i).nombre;
            str[i][1] = filtra.get(i).apellidos;
            str[i][2] = filtra.get(i).dni;
        }
        
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                str,
                new String[]{
                    "Nombre", "Apellidos", "DNI"
                }
        ));
        
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(65);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(80);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
